### PR TITLE
Fixes: Large looping structures, errors triggered multiple times

### LINKED ISSUE #1: Produces multiple errors if one job errors
This can be seen in the test output

### PR DESCRIPTION
**Pull request by tommoor**
closes #1

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -27,64 +27,50 @@ class PromisePool {
...
 
-    // The number of promises running is enough or there are no more promises
-    // left to queue up then wait. This avoids a hot-loop.
-    if (this.pool.length >= this.concurrency || !this.queue.length) {
-      if (!this.wait) this.wait = defer();
-      await this.wait.promise;
-      return this.next();
-    }
+    // The number of promises running is enough or there are no more promises left to queue up then wait.
+    if (this.pool.length >= this.concurrency || !this.queue.length) return;
```
Comment (tommoor) [inline src/index.js]: 🍖
